# Generated by Django 5.0.4 on 2024-05-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_track', '0003_rename_from_account_transaction_income_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='to_account',
            new_name='expense_account',
        ),
    ]
